/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scorecard;

import scorecard.repo.Match;
import scorecard.service.impl.ScoreBoardService;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Objects;

public class ScoreBoard {
    List<Match> matches = new ArrayList<>();
    String game;
    ScoreBoardService scoreBoardService;

    public ScoreBoard(String game) {
        this.game = game;
        scoreBoardService = ScoreBoardService.getInstance();
    }

    public Match createMatch(LinkedHashSet<String> teams) {
        if (teams == null || teams.isEmpty() || teams.stream().anyMatch(Objects::isNull)) {
            throw new RuntimeException("Valid teams names expected");
        }
        Match match = scoreBoardService.createMatch(this.game, teams, this);
        // adding it to the scoreboard
        this.matches.add(match);
        return match;
    }

    public List<Match> getMatches() {
        return this.matches;
    }

    public void updateScore() {
    }
}
