/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scorecard;

import scorecard.match.Match;

public class ScoreCard {
    public Match createMatch() {
        ScoreCardService scoreCardService = ScoreCardService.getInstance();
        return scoreCardService.createMatch();
    }
}
