/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scorecard;

import org.junit.jupiter.api.Test;
import scorecard.match.Match;

import static org.junit.jupiter.api.Assertions.*;

class ScoreCardTest {
    @Test void When_CreateMatch_Invoked_Should_CreateMatchInstance() {
        ScoreCard scoreCard = new ScoreCard();
        assertInstanceOf(Match.class , scoreCard.createMatch());
    }
}
